(()=>{"use strict";
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const state={live:JSON.parse(localStorage.getItem("cp.live")??"true"),notify:JSON.parse(localStorage.getItem("cp.notify")??"true"),theme:localStorage.getItem("cp.theme")||"dark",compact:JSON.parse(localStorage.getItem("cp.compact")??"false"),timer:null,range:"24H"};
const resources=[
{name:"web-prod-01",type:"Compute",provider:"AWS",region:"eu-central-1",status:"Running",u:61,c:182},{name:"web-prod-02",type:"Compute",provider:"AWS",region:"eu-central-1",status:"Running",u:54,c:182},{name:"worker-prod-01",type:"Compute",provider:"Azure",region:"Germany West",status:"Running",u:47,c:146},{name:"analytics-node-01",type:"Compute",provider:"GCP",region:"europe-west3",status:"Standby",u:12,c:96},{name:"postgres-primary",type:"Database",provider:"AWS",region:"eu-central-1",status:"Healthy",u:58,c:318},{name:"postgres-replica",type:"Database",provider:"AWS",region:"eu-central-1",status:"Healthy",u:36,c:210},{name:"redis-cache",type:"Database",provider:"Azure",region:"Germany West",status:"Maintenance",u:72,c:118},{name:"assets-prod",type:"Storage",provider:"AWS",region:"eu-central-1",status:"Healthy",u:67,c:224},{name:"backup-vault",type:"Storage",provider:"Azure",region:"Germany West",status:"Healthy",u:43,c:94},{name:"global-edge",type:"Network",provider:"Cloudflare",region:"Global",status:"Healthy",u:38,c:126},{name:"prod-vpc",type:"Network",provider:"AWS",region:"eu-central-1",status:"Healthy",u:29,c:72},{name:"api-gateway",type:"Network",provider:"AWS",region:"eu-central-1",status:"Degraded",u:81,c:74}];
let incidents=[
{id:"INC-1042",title:"Elevated latency on API Gateway",service:"API Gateway",sev:"High",status:"Investigating",age:"7 min"},{id:"INC-1041",title:"Redis cache memory pressure",service:"Redis Cache",sev:"Medium",status:"Monitoring",age:"24 min"},{id:"INC-1039",title:"Intermittent storage retry events",service:"Object Storage",sev:"Low",status:"Identified",age:"1h 12m"},{id:"INC-1037",title:"Database connection saturation",service:"PostgreSQL",sev:"Medium",status:"Resolved",age:"Yesterday"},{id:"INC-1032",title:"CDN origin timeout spike",service:"Edge Network",sev:"Low",status:"Resolved",age:"3 days"}];
const logs=[["09:44:22","SUCCESS","autoscaler","Scaled web-prod group from 5 to 6 instances"],["09:43:51","INFO","api-gateway","Health check completed — 17/18 upstream targets healthy"],["09:42:18","WARN","redis-cache","Memory utilization exceeded 70% warning threshold"],["09:40:06","SUCCESS","deployment","Deployment cloudpulse-api v2.4.0 completed successfully"],["09:38:27","INFO","postgres-primary","Automated backup completed in 94 seconds"],["09:35:42","ERROR","api-gateway","Upstream request timeout from checkout-service"],["09:34:10","INFO","security","WAF ruleset refreshed — 48 managed rules active"],["09:29:58","SUCCESS","iam","Service account token rotated automatically"],["09:25:13","INFO","cdn","Cache hit ratio: 94.7% across 32 edge locations"],["09:18:02","WARN","cost-analyzer","3 underutilized compute instances detected"],["09:12:45","INFO","monitoring","Synthetic transaction check passed in Frankfurt"],["09:05:32","SUCCESS","terraform","Infrastructure drift scan completed — no drift found"],["08:58:09","INFO","postgres-replica","Replication lag: 142ms"],["08:51:31","INFO","storage","Object lifecycle policy processed 2,411 objects"],["08:42:17","SUCCESS","backup","Nightly backup verification passed"],["08:31:59","INFO","network","VPC flow log export completed"],["08:22:11","WARN","worker-prod-01","CPU burst above 85% for 90 seconds"],["08:14:44","INFO","identity","MFA policy compliance: 100%"]];
const activities=[["Production deployment completed","cloudpulse-api v2.4.0","4 min ago"],["Autoscaler added an instance","web-prod group · +1 node","7 min ago"],["Backup completed","postgres-primary · 18.3 GB","11 min ago"],["Security rules refreshed","WAF managed ruleset","16 min ago"]];
const notices=[["!","API Gateway latency elevated","P95 latency reached 286 ms. Incident INC-1042 is investigating."],["↘","Cost optimization found","Three compute instances are candidates for rightsizing."],["✓","Deployment successful","cloudpulse-api v2.4.0 reached all production targets."],["⟳","Backup verified","The latest PostgreSQL backup passed integrity verification."]];
function init(){apply();bind();renderResources();renderIncidents();renderLogs();renderActivity();renderNotices();renderOverviewIncidents();renderBars();drawAll();start();fromHash()}
function apply(){document.documentElement.dataset.theme=state.theme;document.body.classList.toggle("compact",state.compact);$("#darkModeSetting").checked=state.theme==="dark";$("#compactSetting").checked=state.compact;$("#liveSimulationSetting").checked=state.live;$("#notificationSetting").checked=state.notify}
function bind(){$$(".nav-item").forEach(a=>a.onclick=e=>{e.preventDefault();go(a.dataset.section)});$$("[data-nav]").forEach(b=>b.onclick=()=>go(b.dataset.nav));window.onhashchange=fromHash;$("#menuButton").onclick=()=>{$("#sidebar").classList.add("open");$("#overlay").classList.add("active")};$("#overlay").onclick=()=>{closeDrawer();$("#sidebar").classList.remove("open");$("#overlay").classList.remove("active")};$("#themeToggle").onclick=toggleTheme;$("#darkModeSetting").onchange=e=>setTheme(e.target.checked?"dark":"light");$("#compactSetting").onchange=e=>{state.compact=e.target.checked;document.body.classList.toggle("compact",state.compact);localStorage.setItem("cp.compact",JSON.stringify(state.compact));toast("Interface updated",state.compact?"Compact density enabled.":"Comfortable density enabled.")};$("#liveSimulationSetting").onchange=e=>{state.live=e.target.checked;localStorage.setItem("cp.live",JSON.stringify(state.live));state.live?start():stop();toast("Telemetry preference saved",state.live?"Live simulation is running.":"Live simulation is paused.")};$("#notificationSetting").onchange=e=>{state.notify=e.target.checked;localStorage.setItem("cp.notify",JSON.stringify(state.notify));toast("Notification preference saved",state.notify?"Demo notifications enabled.":"Demo notifications disabled.")};$("#notificationButton").onclick=openDrawer;$("#closeDrawer").onclick=closeDrawer;$("#exportButton").onclick=exportCSV;$("#resourceSearch").oninput=renderResources;$("#resourceFilter").onchange=renderResources;$("#refreshResources").onclick=()=>{renderResources();toast("Inventory refreshed","Cloud resource metadata is up to date.")};$("#incidentFilter").onchange=renderIncidents;$("#createIncidentButton").onclick=openModal;$("#closeModal").onclick=closeModal;$("#cancelIncident").onclick=closeModal;$("#incidentForm").onsubmit=createIncident;$("#logSearch").oninput=renderLogs;$("#logLevelFilter").onchange=renderLogs;$("#clearFilters").onclick=()=>{$("#logSearch").value="";$("#logLevelFilter").value="all";renderLogs()};$("#simulateSaving").onclick=()=>{let v=286+Math.floor(Math.random()*44);$("#savingValue").textContent=v;toast("Optimization scan complete",`Potential savings updated to €${v}/month.`)};$$(".optimize").forEach(b=>b.onclick=()=>toast("Demo recommendation","A real system would open a remediation workflow."));$$("#rangeControl button").forEach(b=>b.onclick=()=>{$$("#rangeControl button").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.range=b.dataset.range;drawUtil()});window.onresize=debounce(drawAll,120)}
function fromHash(){let id=location.hash.slice(1)||"overview";if($("#"+id))activate(id)}
function go(id){if(location.hash!=="#"+id)history.pushState(null,"","#"+id);activate(id)}
function activate(id){$$(".view").forEach(v=>v.classList.toggle("active",v.id===id));$$(".nav-item").forEach(a=>a.classList.toggle("active",a.dataset.section===id));$("#pageTitle").textContent=$("#"+id).dataset.title;$("#sidebar").classList.remove("open");$("#overlay").classList.remove("active");scrollTo({top:0,behavior:"smooth"});requestAnimationFrame(drawAll)}
function setTheme(t){state.theme=t;document.documentElement.dataset.theme=t;$("#darkModeSetting").checked=t==="dark";localStorage.setItem("cp.theme",t);drawAll()}function toggleTheme(){setTheme(state.theme==="dark"?"light":"dark")}
function renderResources(){let q=($("#resourceSearch")?.value||"").toLowerCase(),f=$("#resourceFilter")?.value||"all";$("#resourceTableBody").innerHTML=resources.filter(r=>(f==="all"||r.type===f)&&Object.values(r).join(" ").toLowerCase().includes(q)).map(r=>{let w=["Maintenance","Degraded","Standby"].includes(r.status);return`<tr><td><strong>${esc(r.name)}</strong></td><td>${r.type}</td><td>${r.provider}</td><td>${r.region}</td><td><span class="table-status ${w?"warn":""}">${r.status}</span></td><td><div class="util"><i><b style="width:${r.u}%"></b></i>${r.u}%</div></td><td>€${r.c}</td></tr>`}).join("")}
function renderIncidents(){let f=$("#incidentFilter")?.value||"all";$("#incidentTable").innerHTML=incidents.filter(i=>f==="all"||i.sev===f).map(i=>`<div class="incident-card"><span class="sev ${i.sev}"></span><p><b>${esc(i.title)}</b><small>${i.id} · ${esc(i.service)}</small></p><div class="meta"><span>${i.sev}</span><span>${i.status}</span><span>${i.age}</span></div>${i.status!=="Resolved"?`<button class="small-btn resolve" data-id="${i.id}">Resolve</button>`:`<span class="status ok">Resolved</span>`}</div>`).join("");$$(".resolve").forEach(b=>b.onclick=()=>resolve(b.dataset.id));counts()}
function renderOverviewIncidents(){$("#overviewIncidents").innerHTML=incidents.filter(i=>i.status!=="Resolved").slice(0,3).map(i=>`<div class="incident-mini"><span class="sev ${i.sev}"></span><p><b>${esc(i.title)}</b><small>${i.id} · ${i.age}</small></p><button data-nav="incidents">Open →</button></div>`).join("");$$("[data-nav]",$("#overviewIncidents")).forEach(b=>b.onclick=()=>go(b.dataset.nav))}
function counts(){let n=incidents.filter(i=>i.status!=="Resolved").length;$("#incidentBadge").textContent=n;$("#openIncidentCount").textContent=n}
function resolve(id){let i=incidents.find(x=>x.id===id);if(!i)return;i.status="Resolved";i.age="just now";renderIncidents();renderOverviewIncidents();toast("Incident resolved",`${id} has been marked as resolved.`)}
function openModal(){$("#incidentModal").classList.add("open");setTimeout(()=>$("#incidentForm input").focus(),80)}function closeModal(){$("#incidentModal").classList.remove("open")}
function createIncident(e){e.preventDefault();let f=new FormData(e.currentTarget),id="INC-"+(1043+incidents.length);incidents.unshift({id,title:f.get("title"),service:f.get("service"),sev:f.get("severity"),status:"Investigating",age:"just now"});e.currentTarget.reset();closeModal();renderIncidents();renderOverviewIncidents();toast("Test incident created",`${id} added to the incident queue.`)}
function renderLogs(){let q=($("#logSearch")?.value||"").toLowerCase(),f=$("#logLevelFilter")?.value||"all";$("#logConsole").innerHTML=logs.filter(r=>(f==="all"||r[1]===f)&&r.join(" ").toLowerCase().includes(q)).map(r=>`<div class="log"><span>${r[0]}</span><b class="${r[1]}">${r[1]}</b><span>${r[2]}</span><span>${r[3]}</span></div>`).join("")}
function renderActivity(){$("#overviewActivity").innerHTML=activities.map(a=>`<div class="timeline"><i></i><p><b>${a[0]}</b><small>${a[1]}</small></p><time>${a[2]}</time></div>`).join("")}
function renderNotices(){$("#notificationList").innerHTML=notices.map(n=>`<div class="notification"><span>${n[0]}</span><p><b>${n[1]}</b><small>${n[2]}</small></p></div>`).join("")}
function openDrawer(){$("#notificationDrawer").classList.add("open");$("#overlay").classList.add("active")}function closeDrawer(){$("#notificationDrawer").classList.remove("open");if(!$("#sidebar").classList.contains("open"))$("#overlay").classList.remove("active")}
function renderBars(){let v=[42,61,47,70,55,76,65,87,58,68,82,74,92,78,88,66,84,95,73,89,79,97,86,91];$("#trafficBars").innerHTML=v.map(x=>`<span style="height:${x}%"></span>`).join("")}
function start(){stop();if(!state.live)return;state.timer=setInterval(update,3200)}function stop(){if(state.timer)clearInterval(state.timer);state.timer=null}
function update(){let cpu=clamp(+$(" #cpuValue".trim()).textContent+rnd(-4,4),28,79),mem=clamp(+$("#memoryValue").textContent+rnd(-2,2),52,84),lat=clamp(+$("#latencyValue").textContent+rnd(-5,5),55,129);$("#cpuValue").textContent=Math.round(cpu);$("#cpuBar").style.width=cpu+"%";$("#memoryValue").textContent=Math.round(mem);$("#memoryBar").style.width=mem+"%";$("#latencyValue").textContent=Math.round(lat);$("#lastUpdated").textContent="just now";$$("#trafficBars span").forEach(b=>b.style.height=clamp(parseFloat(b.style.height)+rnd(-13,13),22,100)+"%")}
function exportCSV(){let rows=[["CloudPulse Dashboard Report"],["Generated",new Date().toISOString()],[],["Metric","Value"],["CPU Usage",$("#cpuValue").textContent+"%"],["Memory Usage",$("#memoryValue").textContent+"%"],["Uptime",$("#uptimeValue").textContent+"%"],["Estimated Monthly Cost","€"+$("#monthlyCost").textContent],["Open Incidents",incidents.filter(i=>i.status!=="Resolved").length],[],["Resource","Type","Provider","Region","Status","Utilization","Monthly Cost"],...resources.map(r=>[r.name,r.type,r.provider,r.region,r.status,r.u+"%","€"+r.c])];let csv=rows.map(r=>r.map(csvEsc).join(",")).join("\\n"),blob=new Blob([csv],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`cloudpulse-report-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);toast("Report exported","CSV report downloaded successfully.")}
function colors(){let c=getComputedStyle(document.documentElement);return{p:c.getPropertyValue("--purple").trim(),b:c.getPropertyValue("--blue").trim(),g:c.getPropertyValue("--green").trim(),t:c.getPropertyValue("--muted").trim(),grid:c.getPropertyValue("--border").trim()}}
function prep(canvas){if(!canvas||canvas.offsetParent===null)return null;let r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.floor(r.width*d));canvas.height=Math.max(1,Math.floor(r.height*d));let x=canvas.getContext("2d");x.setTransform(d,0,0,d,0,0);return{x,w:r.width,h:r.height}}
function line(canvas,series,labels=[]){let z=prep(canvas);if(!z)return;let{x,w,h}=z,c=colors(),p={l:32,r:12,t:14,b:28},cw=w-p.l-p.r,ch=h-p.t-p.b;x.clearRect(0,0,w,h);x.font="8px Inter";x.fillStyle=c.t;x.strokeStyle=c.grid;for(let i=0;i<=4;i++){let y=p.t+ch*i/4;x.beginPath();x.moveTo(p.l,y);x.lineTo(w-p.r,y);x.stroke();x.fillText(String(100-i*25),4,y+3)}let n=Math.max(...series.map(s=>s.data.length)),step=cw/(n-1||1),idx=[0,Math.floor((n-1)/4),Math.floor((n-1)/2),Math.floor((n-1)*3/4),n-1];idx.forEach(i=>{if(i<0)return;let xx=p.l+i*step;x.fillText(String(labels[i]??""),Math.min(xx-9,w-30),h-7)});series.forEach(s=>{let pts=s.data.map((v,i)=>({x:p.l+i*step,y:p.t+ch-(v/100)*ch})),grad=x.createLinearGradient(0,p.t,0,p.t+ch);grad.addColorStop(0,alpha(s.color,.22));grad.addColorStop(1,alpha(s.color,0));x.beginPath();x.moveTo(pts[0].x,pts[0].y);for(let i=1;i<pts.length;i++){let a=pts[i-1],b=pts[i],cp=(a.x+b.x)/2;x.bezierCurveTo(cp,a.y,cp,b.y,b.x,b.y)}x.lineTo(pts.at(-1).x,p.t+ch);x.lineTo(pts[0].x,p.t+ch);x.closePath();x.fillStyle=grad;x.fill();x.beginPath();x.moveTo(pts[0].x,pts[0].y);for(let i=1;i<pts.length;i++){let a=pts[i-1],b=pts[i],cp=(a.x+b.x)/2;x.bezierCurveTo(cp,a.y,cp,b.y,b.x,b.y)}x.strokeStyle=s.color;x.lineWidth=1.8;x.stroke()})}
function bars(canvas,vals,labels){let z=prep(canvas);if(!z)return;let{x,w,h}=z,c=colors(),p={l:36,r:12,t:14,b:30},cw=w-p.l-p.r,ch=h-p.t-p.b,max=Math.ceil(Math.max(...vals)/500)*500;x.clearRect(0,0,w,h);x.font="8px Inter";x.fillStyle=c.t;x.strokeStyle=c.grid;for(let i=0;i<=4;i++){let y=p.t+ch*i/4;x.beginPath();x.moveTo(p.l,y);x.lineTo(w-p.r,y);x.stroke();x.fillText("€"+Math.round(max*(1-i/4)),2,y+3)}let gap=Math.max(8,cw/vals.length*.35),bw=(cw-gap*(vals.length-1))/vals.length;vals.forEach((v,i)=>{let bh=v/max*ch,xx=p.l+i*(bw+gap),yy=p.t+ch-bh,g=x.createLinearGradient(0,yy,0,p.t+ch);g.addColorStop(0,c.p);g.addColorStop(1,alpha(c.b,.65));round(x,xx,yy,bw,bh,5);x.fillStyle=g;x.fill();x.fillStyle=c.t;x.fillText(labels[i],xx+Math.max(0,bw/2-9),h-8)})}
function drawUtil(){let c=colors(),d={"1H":[[34,38,41,45,39,52,49,44,48,42,46,43],[61,63,66,64,67,69,70,68,69,67,68,68],["-60m","","","","","","-30m","","","","","now"]],"24H":[[31,34,33,37,41,38,44,49,46,52,55,48,44,47,51,57,54,49,46,43,45,40,44,42],[58,59,61,60,62,63,64,63,65,66,68,69,70,69,68,71,72,70,69,68,67,69,68,68],["00:00","","","","","","06:00","","","","","","12:00","","","","","","18:00","","","","","23:00"]],"7D":[[39,46,42,53,48,44,42],[63,67,66,71,70,69,68],["Wed","Thu","Fri","Sat","Sun","Mon","Tue"]],"30D":[[41,47,44,49,52,48,45,51,43,46,50,54,49,48,44],[62,64,66,65,69,70,68,71,67,66,68,70,69,67,68],["Sep 1","","","","","","Sep 14","","","","","","","","Sep 30"]]}[state.range];line($("#utilizationChart"),[{data:d[0],color:c.p},{data:d[1],color:c.b}],d[2])}
function drawAll(){drawUtil();let c=colors();line($("#throughputChart"),[{data:[31,35,41,37,43,48,52,49,58,61,55,64,70,66,72,69,78,74,81,76,84,79,86,83],color:c.g}],["00:00","","","","","","06:00","","","","","","12:00","","","","","","18:00","","","","","23:00"]);bars($("#costChart"),[1390,1485,1560,1634,1720,1842],["Apr","May","Jun","Jul","Aug","Sep"])}
function round(x,a,b,w,h,r){r=Math.min(r,w/2,h/2);x.beginPath();x.moveTo(a+r,b);x.arcTo(a+w,b,a+w,b+h,r);x.arcTo(a+w,b+h,a,b+h,r);x.arcTo(a,b+h,a,b,r);x.arcTo(a,b,a+w,b,r);x.closePath()}
function alpha(hex,a){if(!hex.startsWith("#"))return hex;let s=hex.slice(1);if(s.length===3)s=s.split("").map(x=>x+x).join("");let n=parseInt(s,16);return`rgba(${n>>16&255},${n>>8&255},${n&255},${a})`}
function toast(title,text){let e=document.createElement("div");e.className="toast";e.innerHTML=`<i></i><p><b>${esc(title)}</b><small>${esc(text)}</small></p>`;$("#toastContainer").appendChild(e);setTimeout(()=>e.remove(),3300)}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function csvEsc(v){let s=String(v??"");return/[",\\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}function rnd(a,b){return Math.random()*(b-a)+a}function clamp(n,a,b){return Math.min(b,Math.max(a,n))}function debounce(f,w){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>f(...a),w)}}
init()})();